spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zymblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    root: warn
    club.zymcloud: info
  file:
    name: log/blog.log
server:
  port: 8083



