spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zymblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    root: info
    club.zymcloud: debug
  file:
    name: log/blog.log

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true